"""
API Proxy Lambda
Proxies API Gateway requests to AgentCore Runtime.
Translates between the OpenAI-compatible API format and AgentCore invocation.
"""

import json
import os
import logging
import uuid
import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)

REGION = os.environ.get("REGION", "us-east-1")
AGENTCORE_RUNTIME_ARN = os.environ.get("AGENTCORE_RUNTIME_ARN", "")

agentcore = boto3.client("bedrock-agentcore-runtime", region_name=REGION)


def handler(event, context):
    """Lambda handler - proxies requests to AgentCore Runtime."""
    logger.info(f"Request: {event.get('routeKey', 'unknown')}")

    route_key = event.get("routeKey", "")

    if route_key == "GET /health":
        return _health_response()

    if route_key == "GET /v1/routing/status":
        return _routing_status()

    if route_key == "POST /v1/chat/completions":
        return _chat_completions(event)

    return {
        "statusCode": 404,
        "body": json.dumps({"error": "Not found"})
    }


def _chat_completions(event: dict) -> dict:
    """Handle chat completions - forward to AgentCore Runtime."""
    try:
        body = json.loads(event.get("body", "{}"))
        messages = body.get("messages", [])
        routing_hints = body.get("routing", {})
        request_id = event.get("headers", {}).get("x-request-id", str(uuid.uuid4()))

        if not messages:
            return {
                "statusCode": 400,
                "body": json.dumps({"error": "Missing required field: messages"})
            }

        # Build payload for AgentCore Runtime
        payload = {
            "prompt": messages[-1].get("content", "") if messages else "",
            "messages": messages,
            "routing": routing_hints,
            "request_id": request_id
        }

        # Generate a unique session ID for stateless requests,
        # or use the one provided for multi-turn conversations
        session_id = (
            event.get("headers", {}).get("x-session-id")
            or f"session-{request_id}-{'0' * 20}"  # pad to 33+ chars
        )

        # Invoke AgentCore Runtime
        response = agentcore.invoke_agent_runtime(
            agentRuntimeArn=AGENTCORE_RUNTIME_ARN,
            sessionId=session_id,
            payload=json.dumps(payload).encode("utf-8")
        )

        # Read response stream
        response_body = ""
        if "body" in response:
            for chunk in response["body"]:
                if "chunk" in chunk:
                    response_body += chunk["chunk"].get("text", "")
                elif "bytes" in chunk:
                    response_body += chunk["bytes"].decode("utf-8")

        # Parse agent response
        try:
            agent_response = json.loads(response_body)
        except json.JSONDecodeError:
            agent_response = {"content": response_body}

        # Format as OpenAI-compatible response
        return {
            "statusCode": 200,
            "headers": {
                "Content-Type": "application/json",
                "X-Request-Id": request_id,
                "X-AI-Model": agent_response.get("model_id", "unknown"),
                "X-AI-Provider": agent_response.get("provider", "unknown"),
                "X-AI-Routed": "true",
                "X-AI-Complexity": agent_response.get("complexity", "unknown"),
                "X-AI-Disclosure": "Response generated by dynamically-selected AI model. See /v1/models/info for details."
            },
            "body": json.dumps({
                "id": f"chatcmpl-{request_id}",
                "object": "chat.completion",
                "created": int(__import__("time").time()),
                "model": agent_response.get("model_id", "routed"),
                "choices": [
                    {
                        "index": 0,
                        "message": {
                            "role": "assistant",
                            "content": agent_response.get("content", agent_response.get("response", ""))
                        },
                        "finish_reason": agent_response.get("stop_reason", "stop")
                    }
                ],
                "usage": {
                    "prompt_tokens": agent_response.get("input_tokens", 0),
                    "completion_tokens": agent_response.get("output_tokens", 0),
                    "total_tokens": (
                        agent_response.get("input_tokens", 0) +
                        agent_response.get("output_tokens", 0)
                    )
                },
                "routing": {
                    "complexity": agent_response.get("complexity"),
                    "model_selected": agent_response.get("model_id"),
                    "provider": agent_response.get("provider"),
                    "latency_ms": agent_response.get("latency_ms"),
                    "escalated": agent_response.get("escalated", False)
                }
            })
        }

    except Exception as e:
        logger.error(f"Chat completions error: {str(e)}", exc_info=True)
        return {
            "statusCode": 502,
            "body": json.dumps({
                "error": {
                    "message": "Failed to process request through LLM router",
                    "type": "router_error",
                    "details": str(e)
                }
            })
        }


def _health_response() -> dict:
    """Health check endpoint."""
    return {
        "statusCode": 200,
        "body": json.dumps({
            "status": "healthy",
            "service": "llm-router",
            "runtime_arn": AGENTCORE_RUNTIME_ARN
        })
    }


def _routing_status() -> dict:
    """Return current routing status (model availability, circuit breakers)."""
    # In production, this would query AppConfig and DynamoDB
    return {
        "statusCode": 200,
        "body": json.dumps({
            "status": "operational",
            "models": {
                "amazon.nova-lite-v1:0": {"status": "available", "provider": "bedrock"},
                "amazon.nova-pro-v1:0": {"status": "available", "provider": "bedrock"},
                "anthropic.claude-sonnet-4-20250514-v1:0": {"status": "available", "provider": "bedrock"},
                "anthropic.claude-opus-4-20250514-v1:0": {"status": "available", "provider": "bedrock"},
            }
        })
    }
